### ISSUE TITLE
Use a bundler to simplify the deployment

### ISSUE THREAD

**Issue by eine** [numworks/setup-msys2#4]
By using a bundler, such as webpack, the deployment can be reduced to three files: `main.js`, `action.yml` and `README.md`. See, for example: https://github.com/1138-4EB/issue-runner/tree/gha-tip

**Comment by Ecco** [comment]
I'm not sure I see the point of this. There are already very few files anyway.

Also I think the fewer tools we use the easier it is for newcomers to contribute 😄

**Comment by 1138-4EB** [comment]
> I'm not sure I see the point of this. There are already very few files anyway.

Are you [sure](https://github.com/numworks/setup-msys2/tree/releases/v1/node_modules)? There are currently ~275 files (14.3MB) in the release, and the relevant files account for 1.93KB. It is true that it is a low number for a typical JavaScript application. However, the JS ecosystem being so bad-performing shouldn't prevent us from being kind with bandwidth and disk usage. Moreover, the current list of files is subject to change (content of `node_modules`), which makes maintaining the project harder.

> Also I think the fewer tools we use the easier it is for newcomers to contribute 😄

Note that #5 is based on `ncc` precisely because that's the bundler suggested/explained in the docs of GitHub Actions: https://help.github.com/en/articles/creating-a-javascript-action#commit-and-push-your-action-to-github

Nonetheless, newcomers can ignore this feature completely. This is only relevant for deployment/releases. Therefore, only maintainers need to be aware of it. Developers who are not maintainers can still execute `node main.js` just as they execute `node index.js` now. Furthermore, including this feature in the codebase does not mean you need to use it. I.e., you can keep the same sources and deploy either unbundled, bundled or both of them.

**Comment by eine** [comment]
I'm closing this because #5 (which is part of [eine/setup-msys2](https://github.com/eine/setup-msys2)) has been tested for some months and it works as expected.
